from __future__ import annotations

import os
from typing import Any

import requests
from dotenv import load_dotenv

load_dotenv()

APIFY_API_BASE = "https://api.apify.com/v2"
DEFAULT_APIFY_ACTOR = "akash9078~youtube-transcript-extractor"


def _env(name: str) -> str:
    return os.getenv(name, "").strip()


def apify_is_configured() -> bool:
    return bool(_env("APIFY_API_TOKEN") and get_apify_actor())


def get_apify_actor() -> str:
    return _env("APIFY_TRANSCRIPT_ACTOR") or DEFAULT_APIFY_ACTOR


def apify_debug_enabled() -> bool:
    return _env("APIFY_DEBUG").lower() in {"1", "true", "yes", "on"}


def _build_actor_input(video_url: str, video_id: str) -> dict[str, Any]:
    mode = _env("APIFY_TRANSCRIPT_INPUT_MODE").lower() or "videoUrls"
    language = _env("APIFY_TRANSCRIPT_LANGUAGE") or "en"

    if mode == "working-default":
        return {
            "language": language,
            "videoUrl": video_url,
        }

    if mode == "urls":
        return {
            "urls": [video_url],
            "language": language,
            "includeEnglishAG": True,
            "includeNonEnglish": True,
        }

    if mode == "starturls":
        return {
            "startUrls": [{"url": video_url}],
            "language": language,
        }

    if mode == "videoid":
        return {
            "videoId": video_id,
            "language": language,
        }

    if mode == "videourl":
        return {
            "language": language,
            "videoUrl": video_url,
        }

    return {
        "videoUrls": [video_url],
        "startUrls": [{"url": video_url}],
        "language": language,
        "includeAutoGenerated": True,
    }


def _normalize_segment_text(value: Any) -> str:
    if isinstance(value, str):
        return value.strip()

    if isinstance(value, list):
        parts: list[str] = []
        for item in value:
            if isinstance(item, str):
                if item.strip():
                    parts.append(item.strip())
            elif isinstance(item, dict):
                text = str(item.get("text", "")).strip()
                if text:
                    parts.append(text)
        return " ".join(parts).strip()

    if isinstance(value, dict):
        text = str(value.get("text", "")).strip()
        return text

    return ""


def _extract_transcript_item(items: list[dict[str, Any]]) -> dict[str, str]:
    transcript_keys = [
        "transcript",
        "transcriptText",
        "fullText",
        "full_text",
        "mergedTranscript",
        "captions",
        "subtitles",
        "text",
    ]
    language_keys = [
        "language",
        "languageCode",
        "transcriptLanguage",
        "transcript_language",
    ]

    for item in items:
        for key in transcript_keys:
            text = _normalize_segment_text(item.get(key))
            if text:
                language = ""
                for lang_key in language_keys:
                    language = str(item.get(lang_key, "")).strip()
                    if language:
                        break
                return {
                    "transcript": text,
                    "transcript_language": language,
                    "transcript_source": "apify",
                }

    return {
        "transcript": "",
        "transcript_language": "",
        "transcript_source": "apify-unavailable",
    }


def fetch_transcript_with_apify(video_id: str) -> dict[str, str]:
    token = _env("APIFY_API_TOKEN")
    actor = get_apify_actor()

    if not token or not actor:
        return {
            "transcript": "",
            "transcript_language": "",
            "transcript_source": "apify-not-configured",
        }

    video_url = f"https://www.youtube.com/watch?v={video_id}"
    actor_input = _build_actor_input(video_url, video_id)
    url = f"{APIFY_API_BASE}/acts/{actor}/run-sync-get-dataset-items"

    try:
        response = requests.post(
            url,
            headers={
                "Authorization": f"Bearer {token}",
                "Content-Type": "application/json",
            },
            json=actor_input,
            timeout=120,
        )
        response.raise_for_status()
    except requests.RequestException as exc:
        debug_message = ""
        status_code = None
        if getattr(exc, "response", None) is not None:
            status_code = exc.response.status_code
            try:
                debug_message = exc.response.text[:2000]
            except Exception:
                debug_message = str(exc)

        if apify_debug_enabled():
            print(
                {
                    "source": "apify_error",
                    "video_id": video_id,
                    "actor": actor,
                    "input": actor_input,
                    "status_code": status_code,
                    "error": debug_message or str(exc),
                }
            )
        return {
            "transcript": "",
            "transcript_language": "",
            "transcript_source": "apify-error",
            "debug_error": debug_message or str(exc),
        }

    try:
        items = response.json()
        if isinstance(items, dict):
            items = [items]
        if not isinstance(items, list):
            items = []
    except ValueError:
        items = []

    result = _extract_transcript_item(items)
    if apify_debug_enabled():
        print(
            {
                "source": "apify_debug",
                "video_id": video_id,
                "actor": actor,
                "input": actor_input,
                "items_count": len(items),
                "sample_keys": list(items[0].keys()) if items and isinstance(items[0], dict) else [],
                "transcript_found": bool(result.get("transcript")),
                "transcript_source": result.get("transcript_source"),
            }
        )
    return result
